sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

install: pip install tox-travis scrutinizer-ocular

script:
 - tox
 - '[[ $TRAVIS_PYTHON_VERSION == 2.6 ]] || tox -e lint'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ocular --data-file ".coverage" --config-file ".coveragerc"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: nicoulaj
  password:
    secure: "PH03sct2gKSxhfefRCNVYUqHGi5gPxBfMBe4ZIdNXR6WbfoLn/tOv1MkIasptABMHkhuSJ+Rr7o4GfsCXUmSuOPdMx9xsFhWyA/HBAeHRJpg4auDPUNIxGn89YJNVsWipJhL9vxjEXhuI1ySzaPR2KQ7wgYa6rfT9yGn34aQUBA="
  on:
    tags: true
    python: 3.6

notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/3d9dabdef1a3d8b2ae8d

addons:
    code_climate:
        repo_token: bbb89d45db24dbc49fc3f63a70050f3864ed607131c35bb1797c7ecdec1fc9b1
